### Add User
# @prompt username
# @prompt password
POST {{host}}/api/users
Content-Type: application/json

{
    "username": "{{username}}",
    "password": "{{password}}"
}

### Login as User
# @name login
# @prompt username
# @prompt password
POST {{host}}/api/users/login
Content-Type: application/json

{
    "username": "{{username}}",
    "password": "{{password}}"
}

###
@token = {{login.response.body.token}}

### Get Users
GET {{host}}/api/users
Authorization: Bearer {{token}}

### Add Grocery

POST {{host}}/api/groceries
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Test Item",
    "aliases": [ "Test", "Test1", "TestOne", "Test One" ],
    "sections": [ "Test Section", "Cheese" ],
    "units": "foo"
}

### Get Groceries
GET {{host}}/api/groceries
Authorization: Bearer {{token}}
Content-Type: application/json
