### --- USERS / LOGIN -------------------------------------------------------------------

### Add User
# @prompt username
# @prompt password
POST {{host}}/api/users
Content-Type: application/json

{
    "username": "{{username}}",
    "password": "{{password}}"
}

### Login as User
# @name login
# @prompt username
# @prompt password
POST {{host}}/api/users/login
Content-Type: application/json

{
    "username": "{{username}}",
    "password": "{{password}}"
}

###
@token = {{login.response.body.token}}

### Get Users
GET {{host}}/api/users
Authorization: Bearer {{token}}

### Modify User
# @prompt userid
PUT {{host}}/api/users/{{userid}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "id": "{{userid}}",
    "isAdmin": true
}

### --- GROCERIES -------------------------------------------------------------------

### Add Grocery
# @prompt name
# @prompt section
POST {{host}}/api/groceries
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "{{name}}",
    "section": "{{section}}",
    "units": null
}

### Get Groceries
GET {{host}}/api/groceries
Authorization: Bearer {{token}}

### Get Grocery by id
# @prompt id
GET {{host}}/api/groceries/{{id}}
Authorization: Bearer {{token}}

### Update Grocery
# @prompt id
# @prompt newname
PUT {{host}}/api/groceries/{{id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "id": {{id}},
    "name": "{{newname}}",
    "units": "oz"
}

### Delete Grocery
# @prompt id
DELETE {{host}}/api/groceries/{{id}}
Authorization: Bearer {{token}}

### --- LISTS -------------------------------------------------------------------

### Add List
# @prompt name
POST {{host}}/api/lists
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "{{name}}"
}

### Get My Lists
GET {{host}}/api/lists
Authorization: Bearer {{token}}

### Get ALL Lists
GET {{host}}/api/lists?all=true
Authorization: Bearer {{token}}

### Get List by id
# @prompt id
GET {{host}}/api/lists/{{id}}
Authorization: Bearer {{token}}

### Update List
# @prompt id
# @prompt newname
PUT {{host}}/api/lists/{{id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "id": {{id}},
    "name": "{{newname}}"
}

### Delete List
# @prompt id
DELETE {{host}}/api/lists/{{id}}
Authorization: Bearer {{token}}

### --- LIST ITEMS -------------------------------------------------------------------

### Add Item to List
# @prompt listId
# @prompt groceryId
# @prompt storeId
# @prompt amount
POST {{host}}/api/lists/{{listId}}/items
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "groceryId": {{groceryId}},
    "storeId": {{storeId}},
    "amount": {{amount}}
}

### Get Items from List
# @prompt listId
GET {{host}}/api/lists/{{listId}}/items
Authorization: Bearer {{token}}

### Get Item by Id
# @prompt listId
# @prompt id
GET {{host}}/api/lists/{{listId}}/items/{{id}}
Authorization: Bearer {{token}}

### Update Item
# @prompt listId
# @prompt id
# @prompt pickedUp
PUT {{host}}/api/lists/{{listId}}/items/{{id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "id": {{id}},
    "pickedUp": {{pickedUp}}
}

### Delete Item from List
# @prompt listId
# @prompt id
DELETE {{host}}/api/lists/{{listId}}/items/{{id}}
Authorization: Bearer {{token}}

### --- STORES -------------------------------------------------------------------

### Add Store
# @prompt name
# @prompt address
POST {{host}}/api/stores
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "{{name}}",
    "address": "{{address}}"
}

### Get Stores
GET {{host}}/api/stores
Authorization: Bearer {{token}}

### Get Store by id
# @prompt id
GET {{host}}/api/stores/{{id}}
Authorization: Bearer {{token}}

### Get Store by id with Aisles & Sections Populated
# @prompt id
GET {{host}}/api/stores/{{id}}?aisles=true
Authorization: Bearer {{token}}

### Update Store
# @prompt id
# @prompt newaddress
PUT {{host}}/api/stores/{{id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "id": {{id}},
    "address": "{{newaddress}}"
}

### Delete Store
# @prompt id
DELETE {{host}}/api/stores/{{id}}
Authorization: Bearer {{token}}

### --- STORE AISLES -------------------------------------------------------------------

### Add Asile
# @prompt storeId
# @prompt name
# @prompt position
POST {{host}}/api/stores/{{storeId}}/aisles
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "{{name}}",
    "position": {{position}}
}

### Get Aisles
# @prompt storeId
GET {{host}}/api/stores/{{storeId}}/aisles
Authorization: Bearer {{token}}

### Reorder Aisles
# @prompt storeId
# @prompt newOrder
PUT {{host}}/api/stores/{{storeId}}/aisles
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "order": [ {{newOrder}} ]
}

### Update Aisle
# @prompt storeId
# @prompt aisleId
# @prompt newname
# @prompt newposition
PUT {{host}}/api/stores/{{storeId}}/aisles/{{aisleId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "id": {{aisleId}},
    "name": "{{newname}}",
    "position": {{newposition}}
}

### Delete Aisle
# @prompt storeId
# @prompt aisleId
DELETE {{host}}/api/stores/{{storeId}}/aisles/{{aisleId}}
Authorization: Bearer {{token}}

### --- STORE SECTIONS -------------------------------------------------------------------

### Add Section
# @prompt storeId
# @prompt aisleId
# @prompt name
POST {{host}}/api/stores/{{storeId}}/aisles/{{aisleId}}/sections
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "{{name}}"
}

### Get Sections
# @prompt storeId
# @prompt aisleId
GET {{host}}/api/stores/{{storeId}}/aisles/{{aisleId}}/sections
Authorization: Bearer {{token}}

### Set ALL Sections
# @prompt storeId
# @prompt aisleId
# @prompt newSections
PUT {{host}}/api/stores/{{storeId}}/aisles/{{aisleId}}/sections
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "sections": [ {{newSections}} ]
}

### Delete Section
# @prompt storeId
# @prompt aisleId
# @prompt name
DELETE {{host}}/api/stores/{{storeId}}/aisles/{{aisleId}}/sections/{{name}}
Authorization: Bearer {{token}}

### Get ALL Sections - that are defined by stores
GET {{host}}/api/sections
Authorization: Bearer {{token}}

### Get ALL Sections - that are defined by the groceries
GET {{host}}/api/sections/groceries
Authorization: Bearer {{token}}

### Get Store Sections
# @prompt storeId
GET {{host}}/api/stores/{{storeId}}/sections
Authorization: Bearer {{token}}